// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    Demo1: typeof import('./components/demo1.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Pop: typeof import('./components/pop.vue')['default']
  }
}

export { }
